jobs:
  - name: ecsfailmani7
    type: manifest
    steps:
      - IN: trigger-dv-man
      - IN: new-tag1
   # on_failure:
      #- ./party.sh
    #  - ls
     # - pwd
 # - name : deployecsfail167
  #  type: ecsDeploy
  #  steps:
   #   - GET: ecsfailmanifest11
    #  - GET: resoproecsfail
    #  - GET: trigger-dv-man
    #on_failure:
      #- ./party.sh
     # - echo 'failed'
    #  - echo 'testing invalid command'
    #  - testfaills



#  - name: script-piperun90
 #   type: runSh
   # serial: true
  #  steps:
   #   - GET: sample-script1
    #  - GET: triggertest1
    #  - TASK:
    #    - script: pwd
    #    - script: ./GET/sample-script/sample-script/echo.sh
        
 # - name: script-piperunShp90
  #  type: runSh
  #  serial: true
  #  steps:
  #    - GET: sample-script1
  #    - GET: triggertest1
  #    - TASK:
   #     - script: ls
    #    - script: ./GET/sample-script/sample-script/echo.sh
  #- name: script-p333
    #type: runSh
    #serial: true
     #steps:
      #- GET: sample-script1
      #- GET: triggertest1  
      #- TASK:
       # - script: ps
        #- script: ./GET/sample-script/sample-script/echo.sh
 

