jobs:
  - name: script-0y101
    type: runSh
    #serial: true
    steps:
      - GET: sample-script1
      - GET: triggertest1
      - TASK:
        - script: pwd
        - script: ./GET/sample-script/sample-script/echo.sh
  - name: script-0y101
    type: runSh
    #serial: true
    steps:
      - GET: sample-script1
      - GET: triggertest2
      - TASK:
        - script: ls
        - script: ./GET/sample-script/sample-script/echo.sh
  - name: script-0y102
    type: runSh
    #serial: true
    steps:
      - GET: sample-script1
      - GET: triggertest3
      - TASK:
        - script: ps
        - script: ./GET/sample-script/sample-script/echo.sh


