jobs:
  - name: ecsmanifests1
    type: manifest
    steps:
      - IN: trigger-dv-man
      - IN: new-image
      #  versionNumber: 1
      - TASK: managed
   # on_failure:
      #- ./party.sh
    #  - ls
     # - pwd
  - name : deployecs63
    type: ecsDeploy
    steps:
      - IN: ecsmanifests1
      - IN: trigger-dv-man
      - IN: test-cluster1
        #versionNumber: 5
      - TASK: managed
       # deployMethod: upgrade
    #on_failure:
      #- ./party.sh
     # - echo 'failed'
    #  - echo 'testing invalid command'
    #  - testfaills



#  - name: script-piperun90
 #   type: runSh
   # serial: true
  #  steps:
   #   - GET: sample-script1
    #  - GET: triggertest1
    #  - TASK:
    #    - script: pwd
    #    - script: ./GET/sample-script/sample-script/echo.sh
        
 # - name: script-piperunShp90
  #  type: runSh
  #  serial: true
  #  steps:
  #    - GET: sample-script1
  #    - GET: triggertest1
  #    - TASK:
   #     - script: ls
    #    - script: ./GET/sample-script/sample-script/echo.sh
  #- name: script-p333
    #type: runSh
    #serial: true
     #steps:
      #- GET: sample-script1
      #- GET: triggertest1  
      #- TASK:
       # - script: ps
        #- script: ./GET/sample-script/sample-script/echo.sh
 

